AEMall/AEMall/Web/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;
//_5_1_a_s_p_x
namespace Web.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/
        ProductTypesBLL _ProductTypesBLL = new ProductTypesBLL();
        ProductsBLL _ProductsBLL = new ProductsBLL();
        ArticlesBLL _ArticlesBLL = new ArticlesBLL();
        ConfigsBLL _ConfigsBLL = new ConfigsBLL();
        UsersBLL _UsersBLL = new UsersBLL();
        public ActionResult Index()
        {
            bool ispower = false;
            string userid = User.Identity.Name;
            if (!String.IsNullOrEmpty(userid))
            {
                Guid UserId = Guid.Parse(userid);
                var user = _UsersBLL.Get(UserId);
                if(user != null)
                    ispower = user.IsPower.HasValue ? user.IsPower.Value : false;
            }
            if(ispower)
                return Redirect("/Admin");
            else
                return View();
        }
        public ActionResult Tabs()
        {
            ViewBag.Hots = _ProductsBLL.GetByTypeName("热销").Take(5);
            ViewBag.MailFree = _ProductsBLL.GetByTypeName("包邮").Take(5);
            ViewBag.Special = _ProductsBLL.GetByTypeName("特色").Take(5);
            ViewBag.Artwork = _ProductsBLL.GetByTypeName("工艺").Take(5);
            return View();
        }
        public ActionResult Regions()
        {
            var items = _ProductsBLL.Get().Take(8);
            return View(items);
        }
        public ActionResult Articles()
        {
            var items = _ArticlesBLL.Get();
            return View(items); 
        }
        public ActionResult LeftTree()
        {
            var items = _ProductTypesBLL.Get().Where(a=>a.ProductTypes2.Name.Equals("按地域分")).Take(11);
            return View(items);
        }
        public ActionResult TopNav()
        {
            var items = _ProductTypesBLL.GetTopNav();
            return View(items);
        }
        //public ActionResult Focus()
        //{
        //    var items = _ArticlesBLL.Get().Where(a => a.Genres.Name.Equals("焦点滚动"));
        //    return View(items);
        //}
        //public ActionResult Hot()
        //{
        //    var items = _ArticlesBLL.Get().Where(a => a.Genres.Name.Equals("焦点滚动"));
        //    return View(items);
        //}
        //public ActionResult LeftFix()
        //{
        //    var item = _ArticlesBLL.Get().Where(a => a.Genres.Name.Equals("焦点滚动")).First();
        //    return View(item);
        //}
        //public ActionResult RightFix()
        //{
        //    var item = _ArticlesBLL.Get().Where(a => a.Genres.Name.Equals("焦点滚动")).First();
        //    return View(item);
        //}
        public ActionResult Footer()
        {
            var items = _ArticlesBLL.Get();
            return View(items);
        }
        public ActionResult Misc()
        {
            var items = _ArticlesBLL.Get();
            int foundNow = DateTime.Now.Year;
            string foundString = foundNow.ToString();
            string foundYear = _ConfigsBLL.Get("YearFounded").Content;
            if (foundYear.IsUint())
            {
                if (foundNow > Int32.Parse(foundYear))
                    foundString = foundYear.ToString() + "-" + foundNow.ToString();
            }
            ViewBag.Founded = foundString;
            ViewBag.Beian = _ConfigsBLL.Get("Beian").Content;
            ViewBag.Address = _ConfigsBLL.Get("Address").Content;
            ViewBag.SysName = _ConfigsBLL.Get("SysName").Content;
            ViewBag.Url = _ConfigsBLL.Get("Url").Content;
            return View(items);
        }
    }
}

AEMall/AEMall/Web/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;

//_5_1_a_s_p_x
namespace Web.Controllers
{
    public class ProductsController : Controller
    {
        //
        // GET: /Products/
        ProductsBLL _ProductsBLL = new ProductsBLL();
        ProductTypesBLL _ProductTypesBLL = new ProductTypesBLL();
        public ActionResult Index(int? pageIndex)
        {
            var products = _ProductsBLL.Get().OrderByDescending(a => a.CreateTime);
            ViewBag.SiteName = "测试1";
            return View(products.ToPagedList(pageIndex));
        }
        public ActionResult Search(int? pageIndex, string keywords)
        {
            var products = _ProductsBLL.Get().Where(a => a.Brand.Contains(keywords) || a.Description.Contains(keywords) || a.Keywords.Contains(keywords) || a.Name.Contains(keywords) || a.Regions.Name.Contains(keywords)).OrderByDescending(a => a.CreateTime);
            return View(products.ToPagedList(pageIndex));
        }
        public ActionResult Details(Guid Id)
        {
            var product = _ProductsBLL.Get(Id);
            return View(product);
        }
        public ActionResult Type(int? pageIndex, Guid? Id)
        {
            ViewBag.ProductType = _ProductTypesBLL.Get(Id).Name;
            var products = _ProductsBLL.GetByTypeId(Id).OrderByDescending(a=>a.CreateTime);
            return View(products.ToPagedList(pageIndex));
        }
        public ActionResult RankList()
        {
            var products = _ProductsBLL.Get().Take(10);
            return View(products);
        }
    }
}

AEMall/AEMall/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>物华天宝网 - 追溯原产地，挑选前三强，根绝伪劣货，保证真品质 - 互联网最值得您信赖的特产购物网站 - @ViewBag.Title</title>
    <meta name="description" content="易购同城网-专业同城网上购物商城,产品包括数码、家电、手机、电脑配件、网络产品等数万种商品直销,便捷，诚信的服务,为您提供愉悦的网上商城购物体验!" />
    <meta name="Keywords" content="网上购物,网上商城,手机,笔记本,电脑,MP3,CD,VCD,DV,相机,数码,配件,手表,存储卡,易购同城" />
    <link href="@Url.Content("~/fav.ico")" rel="shortcut icon" />
    <link href="@Url.Content("~/Content/themes/shine/ui.shine.css")" rel="stylesheet" type="text/css" />
    <link href="@ViewBag.CssSelf" rel="stylesheet" type="text/css" />
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.4.4.js")"></script>
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery.switchable-2.0.min.js")"></script>
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery.MSClass.js")"></script>
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery.cloud-zoom.1.0.2.js")"></script>
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>
    <script language="javascript" type="text/javascript" src="@Url.Content("~/Scripts/jquery.common.js")"></script>
    <script language="javascript" type="text/javascript" src="@ViewBag.JsSelf"></script>
</head>
<body>
    <div id="top">
        <span id="fav"><a href="javascript:void(0);">收藏物华天宝网</a></span> <span id="welcome">@Html.Partial("_LogOnPartial")</span>
        <span id="func"><a href=".">我的订单</a> | <a href=".">收藏夹</a> | <a href=".">帮助中心</a></span>
    </div>
    <div id="nav_wrapper">
        <div id="logo">
            @Html.ActionLink("物华天宝网", "Index", "Index")
        </div>
        <div id="slogan">
        </div>
        <div id="lucky">
            <a href="." title="每日幸运好礼">今日幸运好礼</a>
        </div>
        <div id="nav">
            <div id="cat_wrapper" class="cat_hover">
                <div id="cat">
                    <ul>
                        @{Html.RenderAction("LeftTree", "Index");}
                    </ul>
                    <div id="cat_bottom">
                        @Html.ActionLink("查看所有商品", "Index", "Products")</div>
                </div>
            </div>
            <div id="search"><form id="frm_search" action="@Url.Content("~/Products/Search")">
                <input type="text" id="keywords" name="keywords" value="" class="keyword_empty" />
                <input type="submit" id="submit" value="" class="search_static" /></form>
                <span id="tag">@Html.ActionLink("蓝宝石", "Search", "Products", new { keywords = "蓝宝石" }, null) @Html.ActionLink("天然紫晶洞", "Search", "Products", new { keywords = "天然紫晶洞" }, null) @Html.ActionLink("小琅高", "Search", "Products", new { keywords = "小琅高" }, null)</span>
            </div>
            <div id="cart_wrapper">
                <div id="basket_wrapper">
                    <table>
                        <tr>
                            <td style="width: 50px;">
                                <a href="." target="_blank">
                                    <img src="images/cart001.jpg" /></a>
                            </td>
                            <td>
                                <a href="." target="_blank">【贵州特产】月亮山富硒米</a>
                            </td>
                            <td style="width: 110px; text-align: right">
                                <span class="currency">￥</span><span class="price">4.90</span><span class="quantity">×1</span><br />
                                <a href="." class="del">删除</a>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 50px;">
                                <a href="." target="_blank">
                                    <img src="images/cart002.jpg" /></a>
                            </td>
                            <td>
                                <a href="." target="_blank">【云南特产】原生态野生皂角米 雪莲子 植物胶原蛋白 2件包邮</a>
                            </td>
                            <td style="width: 110px; text-align: right">
                                <span class="currency">￥</span><span class="price">400.99</span><span class="quantity">×100</span><br />
                                <a href="." class="del">删除</a>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 50px;">
                                <a href="." target="_blank">
                                    <img src="images/cart002.jpg" /></a>
                            </td>
                            <td>
                                <a href="." target="_blank">【云南特产】原生态野生皂角米 雪莲子 植物胶原蛋白 2件包邮</a>
                            </td>
                            <td style="width: 110px; text-align: right">
                                <span class="currency">￥</span><span class="price">400.99</span><span class="quantity">×100</span><br />
                                <a href="." class="del">删除</a>
                            </td>
                        </tr>
                        <tr>
                            <td style="width: 50px;">
                                <a href="." target="_blank">
                                    <img src="images/cart002.jpg" /></a>
                            </td>
                            <td>
                                <a href="." target="_blank">【云南特产】原生态野生皂角米 雪莲子 植物胶原蛋白 2件包邮</a>
                            </td>
                            <td style="width: 110px; text-align: right">
                                <span class="currency">￥</span><span class="price">400.99</span><span class="quantity">×100</span><br />
                                <a href="." class="del">删除</a>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" style="text-align: right; position: relative">
                                共<span class="price">2</span>件商品 金额合计：<span class="currency">￥</span><span class="price">400.99</span><br />
                                <a href="." class="check">去购物车结算</a>
                            </td>
                        </tr>
                    </table>
                </div>
                <span id="cart"><a href="javascript:void(0);">购物车 <b>36</b> 件</a></span> <span id="checkin">
                    <a href=".">去结算</a></span>
            </div>
            <div id="home">
                @Html.ActionLink("首页", "Index", "Index", null, null)</div>
            <div id="items">
                @{Html.RenderAction("TopNav", "Index");}
            </div>
        </div>
    </div>
    <div id="main_wrapper">
        @RenderBody()
    </div>
    <div id="footer_wrapper">
        @{Html.RenderAction("Footer", "Index");}
    </div>
    <div id="misc">
        @{Html.RenderAction("Misc", "Index");}
    </div>
</body>
</html>

AEMall/AEMall/Web/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated)
{
    @(new BLL.UsersBLL().GetName(Guid.Parse(Context.User.Identity.Name)))
    @("，欢迎来到物华天宝网！") 
    @Html.ActionLink("[退出]", "LogOff", "Account", null, new { @class = "logout" })
    @("，新用户？") 
    @Html.ActionLink("[免费注册]", "Reg", "Account", null, new { @class = "reg" })
}
else
{@("您好，欢迎来到物华天宝网！") 
    @Html.ActionLink("[请登录]", "LogOn", "Account", null, new { @class = "login" })
    @("，新用户？")     
    @Html.ActionLink("[免费注册]", "Reg", "Account", null, new { @class = "reg" })
}