AEMall/AEMall/Backup/Web/Areas/Admin/Controllers/ArticlesController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BLL;
using Models;

namespace Web.Areas.Admin.Controllers
{
    [NoCache]
    [HandleError]
    [Authorize]
    public class ArticlesController:Controller
    {
		ArticlesBLL _ArticlesBLL = new ArticlesBLL();  
		public ActionResult Index(int? pageIndex, string Keyword)
        {
            var model = _ArticlesBLL.Get();
            if (!string.IsNullOrEmpty(Keyword))
            {
				Keyword = Keyword.Trim();
                model = model.Where(a => a.Name.Contains(Keyword));
            }
            return View(model.ToPagedList(pageIndex));
        }
		public ActionResult Details(Guid? id)
        {          
            var item = _ArticlesBLL.Get(id);
            return View(item);
        }
		public ActionResult Edit(Guid? id)
        {
            PicturesBLL _PicturesBLL = new PicturesBLL();
            GenresBLL _GenresBLL = new GenresBLL();
            var item = _ArticlesBLL.Get(id);
            ViewBag.GenreId = _GenresBLL.GetDropdownlist(item.GenreId);
            ViewBag.ItemString = _PicturesBLL.GetStringByArticleId(id);
            return View(item);
        }
		[HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Guid? id, Articles collection)
        {
            PicturesBLL _PicturesBLL = new PicturesBLL();
            Edit(id);
            if (!ModelState.IsValid)
            {
                return View(collection);
            }
            else
            {
                collection.UserId = Guid.Parse(User.Identity.Name);
                string galleryItems = Request["GalleryItems"].ToString();
                _ArticlesBLL.Save(id, ref collection, galleryItems);
                return RedirectToAction("Index", RouteData.Values);
            }
        }
		[HttpDelete]
        public ActionResult Delete(Guid id)
        {
            _ArticlesBLL.DeleteObject(id);
			return RedirectToAction("Index", RouteData.Values);
        }		
		    
    }
}

AEMall/AEMall/Backup/Web/Areas/Admin/Controllers/RegionsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BLL;
using Models;

namespace Web.Areas.Admin.Controllers
{
    [NoCache]
    [HandleError]
	[Authorize]
    public class RegionsController:Controller
    {
		RegionsBLL _RegionsBLL = new RegionsBLL();  
        public ActionResult Index()
        {
            var models = _RegionsBLL.Get();
            models = models.Where(b => !b.ParentId.HasValue).OrderBy(a => a.Regions2.Sequence).ThenBy(b => b.Sequence);
            ViewBag.TreeList = _RegionsBLL.GetTreeList(models);
            return View();
        }
		public ActionResult Details(Guid? id)
        {          
            var item = _RegionsBLL.Get(id);
            return View(item);
        }
		public ActionResult Edit(Guid? id)
        {
            var item = _RegionsBLL.Get(id);
            ViewBag.ParentId = _RegionsBLL.GetDropdownlist(item.ParentId);
            return View(item);
        }
		[HttpPost]
        public ActionResult Edit(Guid? id, Regions collection)
        {
            Edit(id);
            if (!ModelState.IsValid)
            {
                return View(collection);
            }
            else
            {
                _RegionsBLL.Save(id, ref collection);
                return RedirectToAction("Index", RouteData.Values);
            }
        }
		[HttpDelete]
        public ActionResult Delete(Guid id)
        {
            _RegionsBLL.DeleteObject(id);
			return RedirectToAction("Index", RouteData.Values);
        }		
		    
    }
}

AEMall/AEMall/Backup/Web/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;

namespace Web.Controllers
{
    public class ArticlesController : Controller
    {
        //
        // GET: /Articles/
        ArticlesBLL _ArticlesBLL = new ArticlesBLL();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details(Guid Id)
        {
            var articles = _ArticlesBLL.Get(Id);
            return View(articles);
        }
    }
}

AEMall/AEMall/Backup/Web/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;

//_5_1_a_s_p_x
namespace Web.Controllers
{
    public class ProductsController : Controller
    {
        //
        // GET: /Products/
        ProductsBLL _ProductsBLL = new ProductsBLL();
        ProductTypesBLL _ProductTypesBLL = new ProductTypesBLL();
        public ActionResult Index(int? pageIndex)
        {
            var products = _ProductsBLL.Get().OrderByDescending(a => a.CreateTime);
            ViewBag.SiteName = "测试1";
            return View(products.ToPagedList(pageIndex));
        }
        public ActionResult Search(int? pageIndex, string keywords)
        {
            var products = _ProductsBLL.Get().Where(a => a.Brand.Contains(keywords) || a.Description.Contains(keywords) || a.Keywords.Contains(keywords) || a.Name.Contains(keywords) || a.Regions.Name.Contains(keywords)).OrderByDescending(a => a.CreateTime);
            return View(products.ToPagedList(pageIndex));
        }
        public ActionResult Details(Guid Id)
        {
            var product = _ProductsBLL.Get(Id);
            return View(product);
        }
        public ActionResult Type(int? pageIndex, Guid? Id)
        {
            ViewBag.ProductType = _ProductTypesBLL.Get(Id).Name;
            var products = _ProductsBLL.GetByTypeId(Id).OrderByDescending(a=>a.CreateTime);
            return View(products.ToPagedList(pageIndex));
        }
        public ActionResult RankList()
        {
            var products = _ProductsBLL.Get().Take(10);
            return View(products);
        }
    }
}

AEMall/AEMall/Backup/Web/Views/Index/Articles.cshtml
@model IQueryable<Models.Articles>
@{ Layout = null;}
<div>
    <ul>
        @foreach (var item1 in Model.Where(a => a.Genres.Name.Equals("促销活动")).Take(6) as IQueryable<Models.Articles>)
        {
            <li><a href="." target="_blank">@item1.Name.CutString(25)</a></li>
        }
    </ul>
    <span><a href=".">查看更多>></a></span>
</div>
<div>
    <ul>
        @foreach (var item2 in Model.Where(a => a.Genres.Name.Equals("天宝动态")).Take(6) as IQueryable<Models.Articles>)
        {
            <li><a href="." target="_blank">@item2.Name.CutString(25)</a></li>
        }
    </ul>
    <span><a href=".">查看更多>></a></span>
</div>

AEMall/AEMall/Backup/Web/Views/Index/Focus.cshtml
@model IEnumerable<Models.Articles>
@{ Layout = null;}
<ul>
    @foreach (var item in Model)
    {
        <li><a href="javascript:void(0);" target="_blank">
            <img src="@(new BLL.PicturesBLL().GetFirstPictureOriginal(item.Id))" />
        </a></li>                
    }
</ul>

AEMall/AEMall/Backup/Web/Views/Index/Footer.cshtml
@model IQueryable<Models.Articles>
@{ Layout = null;}
<table id="footer_content">
    <thead>
        <tr>
            <th>
                购物指南
            </th>
            <th class="b">
                配送方式
            </th>
            <th class="c">
                支付方式
            </th>
            <th class="d">
                售后服务
            </th>
            <th class="e">
                特色服务
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <ul>
                    @foreach (var item1 in Model.Where(a => a.Genres.Name.Equals("购物指南")) as IQueryable<Models.Articles>)
                    {
                        <li>&loz;&nbsp;@Html.ActionLink(item1.Name.CutString(15), "Details", "Articles", new { id=item1.Id},null)</li>
                    }
                </ul>
            </td>
            <td>
                <ul>
                     @foreach (var item2 in Model.Where(a => a.Genres.Name.Equals("配送方式")) as IQueryable<Models.Articles>)
                     {
                        <li>&loz;&nbsp;@Html.ActionLink(item2.Name.CutString(15), "Details", "Articles", new { id = item2.Id }, null)</li>
                     }
                </ul>
            </td>
            <td>
                <ul>
                     @foreach (var item3 in Model.Where(a => a.Genres.Name.Equals("支付方式")) as IQueryable<Models.Articles>)
                    {
                        <li>&loz;&nbsp;@Html.ActionLink(item3.Name.CutString(15), "Details", "Articles", new { id = item3.Id }, null)</li>
                    }
                </ul>
            </td>
            <td>
                <ul>
                     @foreach (var item4 in Model.Where(a => a.Genres.Name.Equals("售后服务")) as IQueryable<Models.Articles>)
                    {
                        <li>&loz;&nbsp;@Html.ActionLink(item4.Name.CutString(15), "Details", "Articles", new { id = item4.Id }, null)</li>
                    }
                </ul>
            </td>
            <td>
                <ul>
                    @foreach (var item5 in Model.Where(a => a.Genres.Name.Equals("特色服务")) as IQueryable<Models.Articles>)
                    {
                        <li>&loz;&nbsp;@Html.ActionLink(item5.Name.CutString(15), "Details", "Articles", new { id = item5.Id }, null)</li>
                    }
                </ul>
            </td>
        </tr>
        <tr>
            <td colspan="5" class="bottom">
                &nbsp;
            </td>
        </tr>
    </tbody>
</table>

AEMall/AEMall/Backup/Web/Views/Index/Hot.cshtml
@model IEnumerable<Models.Articles>
@{ Layout = null;}
<ul>
    @foreach (var item in Model)
    {
        <li><a href="javascript:void(0);" target="_blank">
            <img src="@(new BLL.PicturesBLL().GetFirstPictureOriginal(item.Id))" />
        </a></li>                
    }
</ul>

AEMall/AEMall/Backup/Web/Views/Index/Index.cshtml
@{
    ViewBag.Title = "首页1";
    ViewBag.CssSelf = @Url.Content("~/Content/themes/shine/ui.shine.main.css");
    ViewBag.JsSelf = @Url.Content("~/Scripts/jquery.start.main.js");
}
<div id="cat_holder">
</div>
<div id="special">
   @{Html.RenderAction("LeftFix");}
</div>
<div id="promotion">
    <div id="slider_wrapper">
        <div id="slide">
            @{Html.RenderAction("Focus");}
        </div>
    </div>
    <div id="tabpro_wrapper">
        <ul id="tabpro" class="clearfix">
            <li>促销活动</li>
            <li>天宝动态</li>
        </ul>
        <div id="tabcent">
            @{Html.RenderAction("Articles");}
        </div>
    </div>
    <div id="hslider_wrapper">
        <a href="javascript:void(0);" class="prev" title="上翻"></a>
        <div id="hslider">
            @{Html.RenderAction("Hot");}
        </div>
        <a href="javascript:void(0);" class="next" title="下翻"></a>
    </div>
    <div id="corner">
         @{Html.RenderAction("RightFix");}
    </div>
    <div id="bigtabs_wrapper">
        <ul id="bigtabs" class="clearfix">
            <li>热销</li>
            <li>包邮</li>
            <li>特色</li>
            <li>工艺</li>
        </ul>
        <div id="bigtabcent">
            @{Html.RenderAction("Tabs", "Index");}
        </div>
    </div>
</div>
<div id="areas_wrapper">
    <div class="area" id="china">
        <span class="area_title">
            <ul>
                <li><a href=".">北京</a></li>
                <li>|</li>
                <li><a href=".">天津</a></li>
                <li>|</li>
                <li><a href=".">上海</a></li>
                <li>|</li>
                <li><a href=".">广州</a></li>
                <li>|</li>
                <li><a href=".">武汉</a></li>
                <li>|</li>
                <li><a href=".">青岛</a></li>
            </ul>
            <a href="." class="more">更多>></a> </span>
        <div class="area_left">
            @{Html.RenderAction("Regions", "Index");}
        </div>
        <div class="area_right">
            <span class="area_right_title">&loz;&nbsp;中国特产畅销榜</span>
            @{Html.RenderAction("RankList", "Products");}
        </div>
    </div>
    <div class="area" id="oversea">
        <span class="area_title">
            <ul>
                <li><a href=".">英国</a></li>
                <li>|</li>
                <li><a href=".">美国</a></li>
                <li>|</li>
                <li><a href=".">越南</a></li>
                <li>|</li>
                <li><a href=".">日本</a></li>
                <li>|</li>
                <li><a href=".">韩国</a></li>
                <li>|</li>
                <li><a href=".">法国</a></li>
            </ul>
            <a href="." class="more">更多>></a> </span>
        <div class="area_left">
           @{Html.RenderAction("Regions", "Index");}
        </div>
        <div class="area_right">
            <span class="area_right_title">&loz;&nbsp;海外特产畅销榜</span>
            @{Html.RenderAction("RankList", "Products");}
        </div>
    </div>
</div>

AEMall/AEMall/Backup/Web/Views/Index/LeftFix.cshtml
@model Models.Articles
@{ Layout = null;}
<a href="." target="_blank">
    <img src="@(new BLL.PicturesBLL().GetFirstPictureOriginal(Model.Id))" />  
</a>

AEMall/AEMall/Backup/Web/Views/Index/LeftTree.cshtml
@model IQueryable<Models.ProductTypes>
@{ Layout = null;}
@{
    foreach (var item in Model)
    {
    <li><span class="title">@Html.ActionLink(item.Name, "Type", "Products", new { id = item.Id }, null)</span><span class="subTitle">@item.Description</span> </li>
    }   
}

AEMall/AEMall/Backup/Web/Views/Index/Misc.cshtml
@model IQueryable<Models.Articles>
@{ Layout = null;}
<div id="misc_link">
@foreach (var item in Model.Where(a => a.Genres.Name.Equals("其它综合")) as IQueryable<Models.Articles>)
{
    @Html.ActionLink(item.Name.CutString(15), "Details", "Articles", new { id = item.Id }, null)@(" | ")
}</div>

@ViewBag.Beian @ViewBag.Address  Copyright &copy;@ViewBag.Founded <a href="@ViewBag.Url">@ViewBag.SysName</a>  版权所有 

AEMall/AEMall/Backup/Web/Views/Index/Regions.cshtml
@model IQueryable<Models.Products>
@{Layout = null;}
<ul>
    @foreach (var item in Model as IQueryable<Models.Products>)
    { <li><a href="@Url.Action("Details", "Products", new { Id = item.Id })" target="_blank" class="item"> 
                    <img src="@(new BLL.GalleryBLL().GetFirstPicture(item.Id))" alt="" /></a> @Html.ActionLink(item.Name, "Details", "Products", new { Id = item.Id }, null)
                    <span><b class="price">@String.Format("{0:C}", item.SalePrice)</b> <b class="price_old">@String.Format("{0:C}", item.MarketPrice)</b></span>
                    <span>@item.Description.removeHtml().CutString(16)</span> </li>
    }
</ul>

AEMall/AEMall/Backup/Web/Views/Index/RightFix.cshtml
@model Models.Articles
@{ Layout = null;}
<a href="." target="_blank">
    <img src="@(new BLL.PicturesBLL().GetFirstPictureOriginal(Model.Id))" />  
</a>

AEMall/AEMall/Backup/Web/Views/Index/Tabs.cshtml
@{Layout = null;}
<ul>
    @foreach (var item3 in ViewBag.Hots as IQueryable<Models.Products>)
    { <li><a href="@Url.Action("Details", "Products", new { Id = item3.Id })" target="_blank" class="item">
                    <img src="@(new BLL.GalleryBLL().GetFirstPicture(item3.Id))"  alt="" /></a> @Html.ActionLink(item3.Name, "Details", "Products", new { Id = item3.Id }, null)
                    <span><b class="price">@String.Format("{0:C}", item3.SalePrice)</b> <b class="price_old">@String.Format("{0:C}", item3.MarketPrice)</b></span>
                    <span>@item3.Description.removeHtml().CutString(16)</span></li>
    }
</ul>
<ul>
    @foreach (var item4 in ViewBag.MailFree as IQueryable<Models.Products>)
    { <li><a href="@Url.Action("Details", "Products", new { Id = item4.Id })" target="_blank" class="item">
                    <img src="@(new BLL.GalleryBLL().GetFirstPicture(item4.Id))"  alt="" /></a> @Html.ActionLink(item4.Name, "Details", "Products", new { Id = item4.Id }, null)
                    <span><b class="price">@String.Format("{0:C}", item4.SalePrice)</b> <b class="price_old">@String.Format("{0:C}", item4.MarketPrice)</b></span>
                    <span>@item4.Description.removeHtml().CutString(16)</span></li>
    }
</ul>
<ul>
    @foreach (var item5 in ViewBag.Special as IQueryable<Models.Products>)
    { <li><a href="@Url.Action("Details", "Products", new { Id = item5.Id })" target="_blank" class="item">
                    <img src="@(new BLL.GalleryBLL().GetFirstPicture(item5.Id))"  alt="" /></a> @Html.ActionLink(item5.Name, "Details", "Products", new { Id = item5.Id }, null)
                    <span><b class="price">@String.Format("{0:C}", item5.SalePrice)</b> <b class="price_old">@String.Format("{0:C}", item5.MarketPrice)</b></span>
                    <span>@item5.Description.removeHtml().CutString(16)</span></li>
    }
</ul>
<ul>
    @foreach (var item6 in ViewBag.Artwork as IQueryable<Models.Products>)
    { <li><a href="@Url.Action("Details", "Products", new { Id = item6.Id })" target="_blank" class="item">
                    <img src="@(new BLL.GalleryBLL().GetFirstPicture(item6.Id))"  alt="" /></a> @Html.ActionLink(item6.Name, "Details", "Products", new { Id = item6.Id }, null)
                    <span><b class="price">@String.Format("{0:C}", item6.SalePrice)</b> <b class="price_old">@String.Format("{0:C}", item6.MarketPrice)</b></span>
                    <span>@item6.Description.removeHtml().CutString(16)</span></li>
    }
</ul>

AEMall/AEMall/Backup/Web/Views/Index/TopNav.cshtml
@model IQueryable<Models.ProductTypes>
@{ Layout = null;}
@{
    foreach (var item in Model)
    {
    @Html.ActionLink(item.Name, "Type", "Products", new { id = item.Id }, null) @("|")
    }   
}